version: '3.6'

services:

  pio_db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=predictionio
      - POSTGRES_PASSWORD=1234
    volumes:
      - piodata:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
    restart: always
    environment:
      - "cluster.name=pio"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 15s
      timeout: 10s
      retries: 3

  pio_events:
    build:
      context: .
    restart: always
    depends_on:
      - pio_db
      - elasticsearch
    ports:
      - 7070:7070
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7070"]
      interval: 15s
      timeout: 10s
      retries: 3

  pio_app:
    build:
      context: .
    restart: always
    env_file:
      - .env
    depends_on:
      - pio_events
      - pio_db
      - elasticsearch
    volumes:
      - home:/root
      - app:/app
    command: /etc/service/pio_app
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  piodata:
  app:
  home: